#!/bin/bash

# print the usage message
usage() {
	echo -e "Usage: $0 [target]" 1>&2
	exit 1
}
command_exists() {
	if ! command -v """$1" >/dev/null 2>&1; then
		echo "I require the command ""$1 but it's not installed. Abort."
		exit 1
	fi
}

# depts
for i in "nodemon" "ccache"; do
	command_exists "$i"
done

target=${1}

if [ "$target" = "" ]; then
	usage
fi

nodemon -e cc,h,js,cpp,hpp --exec "xmake build && xmake run -w . -- $target"
